EMedicalSolution/EMedicalSolution/Controllers/NecessitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EMedicalSolution.Models;
using EMedicalSolution.App_Start;

namespace EMedicalSolution.Controllers
{
    [SessionTimeout]
    public class NecessitiesController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetNecessities()
        {
            PatientMgmtEntities db = new PatientMgmtEntities();
            {
                var Necessities = db.MedicalNecessities.OrderBy(a => a.ICD10Code).ToList();
                return Json(new
                {
                    data = Necessities.Select(ic => new
                    {
                        ic.ID,
                        ic.ICD10Code,
                        ic.Description,
                        ic.Created,

                    })
                }, JsonRequestBehavior.AllowGet);
            }
        }
       
        [HttpGet]
        public ActionResult Save(int id)
        {
            using (PatientMgmtEntities db = new PatientMgmtEntities())
            {
                var v = db.MedicalNecessities.Where(a => a.ID == id).FirstOrDefault();
                var p = string.Join(",", db.NecessitiesProcedureMappings.Where(x => x.NecessityID == id).Select(x => x.ProcedureID).ToList());

                ViewBag.procedureTypeIDs = p;
                ViewBag.proTypes = db.ProcedureTypes.ToList();
                return View(v);
            }

        }

        [HttpPost]
        public ActionResult Save(MedicalNecessity necessity, string procedureTypeIDs)
        {
            bool status = false;
            var procedureTypeIDsArr = procedureTypeIDs.Split(',');


            if (ModelState.IsValid)
            {
                using (PatientMgmtEntities db = new PatientMgmtEntities())
                {
                    if (necessity.ID > 0)
                    {
                        //edit 
                        var v = db.MedicalNecessities.Where(a => a.ID == necessity.ID).FirstOrDefault();
                        if (v != null)
                        {
                            v.ICD10Code = necessity.ICD10Code;
                            v.Description = necessity.Description;
                            v.Created = DateTime.Now;
                            v.CreatedBy = Convert.ToInt32(Session["userID"].ToString());
                        }
                    }
                    else
                    {
                        //save
                        necessity.Created = DateTime.Now;
                        necessity.CreatedBy = Convert.ToInt32(Session["userID"].ToString());
                        db.MedicalNecessities.Add(necessity);
                    }
                    db.SaveChanges();

                    int last_id = necessity.ID;
                    db.NecessitiesProcedureMappings.RemoveRange(db.NecessitiesProcedureMappings.Where(x => x.NecessityID == last_id));
                    NecessitiesProcedureMapping mapps = new NecessitiesProcedureMapping();
                    //db.SaveChanges();
                    if (procedureTypeIDsArr.Length > 0)
                    {
                        for (var i = 0; i < procedureTypeIDsArr.Length; i++)
                        {
                            mapps.NecessityID = last_id;
                            mapps.ProcedureID = Convert.ToInt32(procedureTypeIDsArr[i]);
                            db.NecessitiesProcedureMappings.Add(mapps);
                            db.SaveChanges();
                        }

                    }
                    status = true;
                }

            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            using (PatientMgmtEntities db = new PatientMgmtEntities())
            {
                var v = db.MedicalNecessities.Where(a => a.ID == id).FirstOrDefault();
                if (v != null)
                {
                    return View(v);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteCondition(int id)
        {
            bool status = false;
            using (PatientMgmtEntities db = new PatientMgmtEntities())
            {
                db.NecessitiesProcedureMappings.RemoveRange(db.NecessitiesProcedureMappings.Where(x => x.NecessityID == id));
                var v = db.MedicalNecessities.Where(a => a.ID == id).FirstOrDefault();
                if (v != null)
                {
                    db.MedicalNecessities.Remove(v);
                    db.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

    }
}

EMedicalSolution/EMedicalSolution/Views/Necessities/Delete.cshtml
@model EMedicalSolution.Models.MedicalNecessity

<h2>Delete Medical Necessities</h2>

@using (Html.BeginForm("Delete", "Necessities", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.ID)
    <div class="w3-row w3-margin-top">
        <div class="w3-half">
            <b>ID</b>
        </div>
        <div class="w3-half">
            @Model.ID
        </div>
    </div>
    <div class="w3-row w3-margin-top">
        <div class="w3-half">
            <b>ICD 10 Code</b>
        </div>
        <div class="w3-half">
            @Model.ICD10Code
        </div>
    </div>
    <div class="w3-row w3-margin-top">
        <div class="w3-half">
            <b>Description</b>
        </div>
        <div class="w3-half">
            @Model.Description
        </div>
    </div>

    <div class="w3-row w3-margin-top">
        <input class="w3-btn-block w3-red" type="submit" value="Delete" />
    </div>
}

EMedicalSolution/EMedicalSolution/Views/Necessities/Index.cshtml
@{
    ViewBag.Title = "Medical Necessities";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}


<div class="w3-container tablecontainer dashboardDiv" id="necessity-tab">
    <div class="w3-center w3-dark-gray">
        <h2>Medical Necessities</h2>
    </div>
    <div class="w3-row w3-padding-16">

        <div class="w3-row w3-padding-16">
            @Html.ActionLink("+ Add Necessity", "Save", "Necessities", new { id = 0 }, new { @class = "popup w3-btn w3-green" })
        </div>
        <div class="w3-responsive">
            <table class="w3-table-all w3-hoverable" id="NecessitiesDataTable">
                <thead>
                    <tr>
                        <th>Disease ID</th>
                        <th>ICD10Code</th>                        
                        <th>Description</th>
                        <th>Created</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @*Table Content Appends Here*@
                </tbody>

            </table>
        </div>
    </div>
</div>


@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/date.format.js"></script>

    <script>
        $(document).ready(function () {
            var oTable = $("#NecessitiesDataTable").DataTable({
                "ajax": {
                    "url": '/Necessities/GetNecessities',
                    "type": 'get',
                    "datatype": "json"
                },
                "columns": [
                    { "data": "ID", "autoWidth": true },
                    { "data": "ICD10Code", "autoWidth": true },
                    { "data": "Description", "autoWidth": true },
                    {
                        "data": "Created", "autoWidth": true, "render": function (data) {
                            var date = new Date(parseInt(data.substr(6)));
                            var sdate = date.format("mmm d, yyyy");
                            return sdate;
                        }
                    },
                   
                    {
                        "data": "ID", "render": function (data) {
                            return '<a class="popup w3-btn w3-orange" href="/Necessities/save/' + data + '">Edit<a>';
                        }
                    },
                    {
                        "data": "ID", "render": function (data) {
                            return '<a class="popup  w3-btn w3-red" href="/Necessities/delete/' + data + '">Delete<a>';
                        }
                    }
                ]
            });

            $('.tablecontainer').on('click', 'a.popup', function (e) {
                e.preventDefault();
                OpenPopup($(this).attr('href'), oTable, "Medical Necessities");
            });
        });
    </script>
}




EMedicalSolution/EMedicalSolution/Views/Necessities/Save - Copy.cshtml


@model EMedicalSolution.Models.MedicalNecessity

<h2>Save</h2>

@using (Html.BeginForm("save", "Necessities", FormMethod.Post, new { id = "save_necessityMappings" }))
{
    if (Model != null && Model.ID > 0)
    {
    @Html.HiddenFor(a => a.ID)
    }
        <div class="w3-row w3-margin-top">
        <label class="w3-text-green">ID</label>
        @Html.TextBoxFor(a => a.ID, new { @class = "w3-input w3-border", Readonly = "readonly" })
        @Html.ValidationMessageFor(a => a.ID)
    </div>
    <div class="w3-row w3-margin-top">
        <label class="w3-text-green">ICD10Code</label>
        @Html.TextBoxFor(a => a.ICD10Code, new { @class = "w3-input w3-border", id="codetypes_nes" })
        @Html.ValidationMessageFor(a => a.ICD10Code)
        <span id="ncs_code" style="color:red;display:none;">this field is required*</span>
    </div>

    <div class="w3-row w3-margin-top">
        <label class="w3-text-green">Description</label>
        @Html.TextAreaFor(a => a.Description, new { @class = "w3-input w3-border" ,id="destypes_nes" })
        @Html.ValidationMessageFor(a => a.Description)
        <span id="ncs_Description" style="color:red;display:none;">this field is required*</span>

    </div>
    var pLists = (List<EMedicalSolution.Models.ProcedureType>)ViewBag.proTypes;

    <div class="w3-row  w3-margin-top">
        <select id="multipleSelectPlist" data-placeholder="Select an option" multiple style="min-width:220px;max-width:220px;">
            @foreach (var item in pLists)
            {
                <option value="@item.ID">@item.Title</option>
            }
        </select>
    </div>
    <div class="w3-row  w3-margin-top">
        <input class="w3-btn-block w3-green" type="button" value="Save" id="submit_mapping" />
    </div>    
        }
        <script type="text/javascript">
            setTimeout(function () {
                $("#multipleSelectPlist").select2();
                var ProceduresId = "";
                $('#multipleSelectPlist').on('change', function () {
                    console.log('Selected Value : ' + $(this).val() + ' - Selected Text : ' + $('#multipleSelectPlist option:selected').text());
                    ProceduresId = $(this).val();
                    //console.log(ProceduresId);
                });
                $("#submit_mapping").on("click", function (e) {
                    var ncs_Description = $("#destypes_nes").val();
                    var ncs_code = $("#codetypes_nes").val();
                    if (ncs_code === undefined || ncs_code === null || ncs_code === "") {
                        $("#ncs_code").css("display", "block");
                        return false;
                    } else {
                        $("#ncs_code").css("display", "none");
                    }
                    if (ncs_Description === undefined || ncs_Description === null || ncs_Description === "")
                    {
                        $("#ncs_Description").css("display", "block");
                        return false;
                    } else
                    {
                        $("#ncs_Description").css("display", "none");
                    }
                   
                $.ajax({
                        type: "POST",
                        url: "/Necessities/save/?ProceduresId=" + ProceduresId,
                        data: $('#save_necessityMappings').serialize(),
                        success: function (data) {
                            $("#ncs_Description").css("display", "none");
                            $("#ncs_Description").css("display", "none");
                            //console.log(data);
                            if (data) {
                                $("#ncs_Description").css("display", "none");
                                $("#ncs_code").css("display", "none");
                                toastr.success("Data save successfully!");
                            //    $(".ajax_loader_save").css("display", "none");
                            //    $(document).find(".saveError").css("display", "none");
                            //    $(document).find("#saveSpecialistData").css("display", "none");
                            //    $(document).find(".specialistRemarksValue").val("");
                            //    $("#ApprovedbySpecialist").css('display', 'block');
                            //    $("#sp_name").text(specialistRemarks);

                            //    $("#specialistRemarksTextBox").css('display', 'none');
                            }
                        },
                        error: function ($data) {
                            toastr.error("Error, The request can not be completed due to some error!");
                        }
                })  
                });
            }, 100);

        </script>

EMedicalSolution/EMedicalSolution/Views/Necessities/Save.cshtml
@model EMedicalSolution.Models.MedicalNecessity

<h2>Save</h2>

@using (Html.BeginForm("save", "Necessities", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model != null && Model.ID > 0)
    {
        @Html.HiddenFor(a => a.ID)
    }
    <div class="w3-row w3-margin-top">
        <label class="w3-text-green">ID</label>
        @Html.TextBoxFor(a => a.ID, new { @class = "w3-input w3-border", Readonly = "readonly" })
        @Html.ValidationMessageFor(a => a.ID)
    </div>
    <div class="w3-row w3-margin-top">
        <label class="w3-text-green">ICD10Code</label>
        @Html.TextBoxFor(a => a.ICD10Code, new { @class = "w3-input w3-border" })
        @Html.ValidationMessageFor(a => a.ICD10Code)
    </div>

    <div class="w3-row w3-margin-top">
        <label class="w3-text-green">Description</label>
        @Html.TextAreaFor(a => a.Description, new { @class = "w3-input w3-border" })
        @Html.ValidationMessageFor(a => a.Description)

    </div>
    var pLists = (List<EMedicalSolution.Models.ProcedureType>)ViewBag.proTypes;

    <div class="w3-row  w3-margin-top">
        <label class="w3-text-green">Select Procedure Type</label><br />
        <select id="multipleSelectPlist" data-placeholder="Select Procedures" class="w3-input w3-border" multiple style="min-width:220px;max-width:220px;">
            @foreach (var item in pLists)
            {
                <option value="@item.ID">@item.Title</option>
            }
        </select>
        <input type="hidden" name="procedureTypeIDs" id="procedureTypeIDs" value="@ViewBag.procedureTypeIDs" />
    </div>
    <div class="w3-row  w3-margin-top">
        <input class="w3-btn-block w3-green" type="submit" value="Save" />
    </div>
}

<script type="text/javascript">
    setTimeout(function () {
        $("#multipleSelectPlist").select2();

        var selectedProceduresArr = $("#procedureTypeIDs").val().split(',');
        $("#multipleSelectPlist").select2('val', selectedProceduresArr);  //Pre-Selected values

        $('#multipleSelectPlist').on('change', function () {
            //console.log('Selected Value : ' + $(this).val() + ' - Selected Text : ' + $('#multipleSelectPlist option:selected').text());
            $("#procedureTypeIDs").val($(this).val());
        });
    }, 100);
</script>